openapi: 3.0.0
info:
  title: 'Swagger LinkeBin'
  description: 'La documentation Linkebin de son api'
  license:
    name: LinkeBin
  version: 4.0.0
servers:
  -
    url: linkebin.swagger.io
    description: 'Api server'
paths:
  /bin:
    get:
      tags:
        - bin
      summary: 'Index of bin'
      operationId: 'App\Controller\BinController::index'
      responses:
        '200':
          description: 'Display index of bin'
          headers:
            x-next:
              description: 'A link to the next page of responses'
              schema:
                type: string
  /bins:
    post:
      tags:
        - bin
      summary: 'Add all bins'
      operationId: createBins
      responses:
        '200':
          description: 'An paged array of bins'
          headers:
            x-next:
              description: 'A link to the next page of responses'
              schema:
                type: string
                $ref: '#/components/schemas/bins'
        '201':
          description: 'Null response'
        default:
          description: 'unexpected error'
  /city:
    get:
      tags:
        - city
      summary: 'Index of city'
      operationId: 'App\Controller\CityController::index'
      responses:
        '200':
          description: 'Display index of city'
          headers:
            x-next:
              description: 'A link to the next page of responses'
              schema:
                type: string
  /cities:
    post:
      tags:
        - city
      summary: 'Create a city'
      operationId: createCities
      responses:
        '200':
          description: 'Create a new city'
          headers:
            x-next:
              description: 'A link to the next page of responses'
              schema:
                type: string
        '201':
          description: 'Null response'
        default:
          description: 'unexpected error'
components:
  schemas:
    bins:
      required:
        - id
        - lat
        - long
        - is_enable
        - created_at
        - updated_at
        - user_bin
        - bin_historics
        - cityBins
      properties:
        id:
          type: integer
        coords:
          type: integer
          format: int32
        is_enable:
          type: boolean
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        user_bin:
          type: integer
        bin_historics:
          type: integer
          format: int32
        cityBins:
          type: integer
          format: int32
      type: object
    bin_historic:
      required:
        - id
        - uuid_bin
        - created_at
        - pickup_at
        - empty
      properties:
        id:
          type: integer
        uuid_bin:
          type: integer
        created_at:
          type: string
          format: date-time
        pickup_date:
          type: string
          format: date-time
        empty:
          type: boolean
          nullable: true
      type: object
    city:
      required:
        - id
        - file_json
        - name
        - region
        - departement
        - cityBins
      properties:
        id:
          type: integer
        file_json:
          type: json
        name:
          type: string
          maxLength: 255
        region:
          type: string
          maxLength: 255
          nullable: true
        departement:
          type: string
          maxLength: 255
          nullable: true
        cityBins:
          type: integer
      type: object
    citybin:
      required:
        - id
        - uuid_bin
        - uuid_city
      properties:
        id:
          type: integer
        uuid_bin:
          type: integer
        uuid_city:
          type: integer
      type: object
    reporthistoric:
      required:
        - id
        - uuid_users_bin
        - created_at
        - degradation
        - bin_full
        - missing
      properties:
        id:
          type: integer
        uuid_users_bin:
          type: integer
        created_at:
          type: string
          format: date-time
        degradation:
          type: boolean
        bin_full:
          type: boolean
        missing:
          type: boolean
      type: object
    users:
      required:
        - id
        - role
        - name
        - created_at
        - updated_at
        - adress
        - password
        - token
        - mail
        - is_enable
        - user_bin
      properties:
        id:
          type: integer
        user_id:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
          nullable: true
        token:
          type: string
          maxLength: 255
        is_enable:
          type: boolean
        user_bin:
          type: integer
      type: object
    usersbin:
      required:
        - id
        - uuid_bin
        - uuid_user
        - created_at
        - report_full
        - reportHistoric
      properties:
        id:
          type: integer
        uuid_bin:
          type: integer
          nullable: false
        uuid_user:
          type: integer
          nullable: false
        created_at:
          type: string
          format: date-time
        report_full:
          type: boolean
          nullable: true
        reportHistoric:
          type: integer
      type: object
